name: winbox-clean
base: core20
version: '3.43'
summary: small utility that allows administration of MikroTik RouterOS
icon: snap/gui/icon.png
description: |
  Winbox is a small utility that allows administration of MikroTik RouterOS using a fast and simple GUI.

  Snap conatins Wine runtime and winbox client.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: i386
    run-on: i386

plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core20
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  gtk-3-themes:
    interface: content
    default-provider: gtk-common-themes
    target: $SNAP/data-dir/themes

parts:
  winbox-clean:
    source: .
    plugin: dump
    stage:
      - usr
    stage-packages:
      - libfreetype6
      - libgtk-3-0
    build-packages:
      - wget
    prime:
      - -README*
    override-build: |
        wget -O winbox32.exe "https://download.mikrotik.com/routeros/winbox/${SNAPCRAFT_PROJECT_VERSION}/winbox.exe"
        wget -O winbox64.exe "https://download.mikrotik.com/routeros/winbox/${SNAPCRAFT_PROJECT_VERSION}/winbox64.exe"
        install -o root -D src/wrapper $SNAPCRAFT_PRIME/winbox-clean
        install -o root -D snap/gui/winbox.desktop $SNAPCRAFT_PRIME/winbox.desktop
        install -o root -D winbox32.exe $SNAPCRAFT_PRIME/usr/libexec/winbox32.exe
        install -o root -D winbox64.exe $SNAPCRAFT_PRIME/usr/libexec/winbox64.exe
        snapcraftctl set-version "${SNAPCRAFT_PROJECT_VERSION}+git"

apps:
  winbox-clean:
    command: winbox-clean
    autostart: winbox.desktop
    desktop: winbox.desktop
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      LC_ALL: "C.UTF-8"
      HOME: $SNAP_USER_COMMON
      TMPDIR: $XDG_RUNTIME_DIR
      XDG_CURRENT_DESKTOP: Unity
      DISABLE_WAYLAND: "1"
      CRYPTOGRAPHY_OPENSSL_NO_LEGACY: "True"
    plugs:
      - desktop
      - home
      - network
      - network-bind
      - wayland
      - icon-themes
      - removable-media
      - wine-runtime-c20
      - wine-7-stable
      - x11
      - gtk3
